-- Migração 6: monitoramento de erros do app.
-- Erros do servidor (falhas da IA) e do celular dos usuários ficam registrados
-- aqui; o admin vê tudo no painel "🩺 Erros" sem depender de print no WhatsApp.
-- Rodar no Supabase: SQL Editor → colar → Run.

create table if not exists public.erros_app (
  id bigint generated by default as identity primary key,
  criado_em timestamptz not null default now(),
  origem text not null,          -- 'extract' (servidor/IA) | 'app' (celular do usuário)
  mensagem text not null,        -- o erro que o usuário viu
  detalhe text,                  -- contexto técnico (status HTTP, modelo, arquivo…)
  user_id uuid references public.profiles (id) on delete set null
);

alter table public.erros_app enable row level security;

-- Só o admin lê e apaga; a ESCRITA é feita apenas pelo servidor
-- (service_role, que ignora RLS) — usuário nenhum insere direto.
create policy "erros select" on public.erros_app
  for select using (public.is_admin());

create policy "erros delete" on public.erros_app
  for delete using (public.is_admin());
